DROP TRIGGER IF EXISTS fare_rules_updated_at ON fare_rules;
DROP TRIGGER IF EXISTS trips_updated_at ON trips;
DROP TRIGGER IF EXISTS operator_profiles_updated_at ON operator_profiles;
DROP TRIGGER IF EXISTS users_updated_at ON users;
DROP FUNCTION IF EXISTS set_updated_at;

DROP TABLE IF EXISTS fcm_tokens;
DROP TABLE IF EXISTS otp_codes;
DROP TABLE IF EXISTS trip_shares;
DROP TABLE IF EXISTS safety_incidents;
DROP TABLE IF EXISTS wallet_recharges;
DROP TABLE IF EXISTS wallet_transactions;
DROP TABLE IF EXISTS trip_locations;
DROP TABLE IF EXISTS trip_events;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS fare_rules;
DROP TABLE IF EXISTS verified_operator_snapshots;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS verification_submissions;
DROP TABLE IF EXISTS car_details;
DROP TABLE IF EXISTS boda_details;
DROP TABLE IF EXISTS operator_profiles;
DROP TABLE IF EXISTS passenger_profiles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS app_config;
DROP TABLE IF EXISTS cities;

DROP TYPE IF EXISTS incident_type;
DROP TYPE IF EXISTS doc_type;
DROP TYPE IF EXISTS car_category;
DROP TYPE IF EXISTS payment_provider;
DROP TYPE IF EXISTS recharge_status;
DROP TYPE IF EXISTS wallet_tx_type;
DROP TYPE IF EXISTS trip_status;
DROP TYPE IF EXISTS verification_status;
DROP TYPE IF EXISTS operator_status;
DROP TYPE IF EXISTS ride_type;
DROP TYPE IF EXISTS operator_type;
DROP TYPE IF EXISTS user_role;
